In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../datasets/traffic_mgmt.csv")

In [4]:
df.head()

,timestamp,location_id,traffic_volume,avg_vehicle_speed,vehicle_count_cars,vehicle_count_trucks,vehicle_count_bikes,weather_condition,temperature,humidity,accident_reported,signal_status
0,2024-01-01 00:00:00,4,504,53.124162,142,24,44,Cloudy,33.334387,36.390698,0,Red
1,2024-01-01 00:01:00,5,209,44.947850,862,50,23,Cloudy,17.926830,37.640927,0,Green
2,2024-01-01 00:02:00,3,572,63.179229,317,12,10,Windy,33.483375,84.262610,1,Red
3,2024-01-01 00:03:00,5,699,42.269697,709,43,21,Sunny,19.212941,61.550978,0,Yellow
4,2024-01-01 00:04:00,5,639,72.185791,594,34,14,Cloudy,11.349244,77.494506,0,Red

In [5]:
df.tail()

,timestamp,location_id,traffic_volume,avg_vehicle_speed,vehicle_count_cars,vehicle_count_trucks,vehicle_count_bikes,weather_condition,temperature,humidity,accident_reported,signal_status
1995,2024-01-02 09:15:00,1,922,71.580775,405,78,48,Cloudy,23.524313,84.628298,1,Red
1996,2024-01-02 09:16:00,5,941,77.568331,81,12,29,Rainy,32.308462,60.169011,1,Yellow
1997,2024-01-02 09:17:00,1,504,33.062751,534,65,30,Windy,26.999638,46.140836,0,Green
1998,2024-01-02 09:18:00,5,62,25.289129,449,18,27,Foggy,27.999731,65.907705,0,Red
1999,2024-01-02 09:19:00,3,259,31.672102,599,23,21,Foggy,12.124246,42.100286,0,Yellow

In [6]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 2000
Columns : 12

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             2000 non-null   str
 1   location_id           2000 non-null   int64
 2   traffic_volume        2000 non-null   int64
 3   avg_vehicle_speed     2000 non-null   float64
 4   vehicle_count_cars    2000 non-null   int64
 5   vehicle_count_trucks  2000 non-null   int64
 6   vehicle_count_bikes   2000 non-null   int64
 7   weather_condition     2000 non-null   str
 8   temperature           2000 non-null   float64
 9   humidity              2000 non-null   float64
 10  accident_reported     2000 non-null   int64
 11  signal_status         2000 non-null   str
dtypes: float64(3), int64(6), str(3)
memory usage: 187.6 KB

In [8]:
df.columns.tolist()

['timestamp',
 'location_id',
 'traffic_volume',
 'avg_vehicle_speed',
 'vehicle_count_cars',
 'vehicle_count_trucks',
 'vehicle_count_bikes',
 'weather_condition',
 'temperature',
 'humidity',
 'accident_reported',
 'signal_status']

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
location_id,2000.0,2.991500,1.430892,1.000000,2.000000,3.000000,4.000000,5.000000
traffic_volume,2000.0,540.959000,271.933985,50.000000,309.000000,549.000000,774.000000,998.000000
avg_vehicle_speed,2000.0,50.009035,17.267898,20.011192,35.168589,50.412652,65.135366,79.972635
vehicle_count_cars,2000.0,449.872500,253.695741,20.000000,227.750000,452.000000,660.250000,899.000000
vehicle_count_trucks,2000.0,49.269000,28.830196,0.000000,24.000000,49.000000,74.000000,99.000000
vehicle_count_bikes,2000.0,24.117000,14.297011,0.000000,12.000000,24.000000,36.000000,49.000000
temperature,2000.0,22.447538,7.200535,10.025557,16.410169,22.364844,28.563564,34.990891
humidity,2000.0,60.105652,17.245294,30.007119,45.179396,60.450407,74.805580,89.989003
accident_reported,2000.0,0.054000,0.226074,0.000000,0.000000,0.000000,0.000000,1.000000

In [10]:
df.isnull().sum()

timestamp               0
location_id             0
traffic_volume          0
avg_vehicle_speed       0
vehicle_count_cars      0
vehicle_count_trucks    0
vehicle_count_bikes     0
weather_condition       0
temperature             0
humidity                0
accident_reported       0
signal_status           0
dtype: int64

In [11]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [12]:
df.dtypes

timestamp                   str
location_id               int64
traffic_volume            int64
avg_vehicle_speed       float64
vehicle_count_cars        int64
vehicle_count_trucks      int64
vehicle_count_bikes       int64
weather_condition           str
temperature             float64
humidity                float64
accident_reported         int64
signal_status               str
dtype: object

In [13]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [14]:
df["Hour"] = df["timestamp"].dt.hour

df["Day"] = df["timestamp"].dt.day

df["Month"] = df["timestamp"].dt.month

df["Weekday"] = df["timestamp"].dt.day_name()

df["Is_Weekend"] = df["timestamp"].dt.dayofweek >= 5df["Congestion_Level"].value_counts()

In [15]:
df["Congestion_Level"].value_counts()

KeyError: 'Congestion_Level'