In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../datasets/traffic.csv")

In [4]:
df.head()

,Timestamp,IR Presence (Lane 1–4),Vehicle Count,Avg Speed (km/h),Vehicle Types Detected,Vehicle Density (%),Traffic Congestion Level
0,08:00:00,"[0, 0, 1, 0]",97,31.2,"10 Bikes, 90 Ambulance, 60 Fire Extinguisher",40,Low
1,08:01:00,"[0, 0, 1, 1]",126,48.5,"32 Ambulance, 94 Ambulance",57,Medium
2,08:02:00,"[1, 0, 0, 0]",61,42.0,"99 Trucks, 76 Patrol, 65 Fire Extinguisher",82,High
3,08:03:00,"[0, 0, 0, 0]",170,38.0,"50 Cars, 71 Patrol, 63 Fire Extinguisher",75,High
4,08:04:00,"[1, 0, 0, 0]",180,24.7,"17 Patrol, 93 Cars, 25 Bikes, 23 Vans",90,High

In [5]:
print(df.shape)

(4354, 7)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4354 entries, 0 to 4353
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Timestamp                 4354 non-null   str
 1   IR Presence (Lane 1–4)    4354 non-null   str
 2   Vehicle Count             4354 non-null   int64
 3   Avg Speed (km/h)          4354 non-null   float64
 4   Vehicle Types Detected    4354 non-null   str
 5   Vehicle Density (%)       4354 non-null   int64
 6   Traffic Congestion Level  4354 non-null   str
dtypes: float64(1), int64(2), str(4)
memory usage: 238.2 KB

In [7]:
df.columns.tolist()

['Timestamp',
 'IR Presence (Lane 1–4)',
 'Vehicle Count',
 'Avg Speed (km/h)',
 'Vehicle Types Detected',
 'Vehicle Density (%)',
 'Traffic Congestion Level']

In [8]:
df.isnull().sum()

Timestamp                   0
IR Presence (Lane 1–4)      0
Vehicle Count               0
Avg Speed (km/h)            0
Vehicle Types Detected      0
Vehicle Density (%)         0
Traffic Congestion Level    0
dtype: int64

In [9]:
print(df.duplicated().sum())

0

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Vehicle Count,4354.0,125.081994,43.230983,50.0,88.0,125.00,162.0,200.0
Avg Speed (km/h),4354.0,34.926757,8.692768,20.0,27.4,35.05,42.4,50.0
Vehicle Density (%),4354.0,59.796279,17.800153,30.0,44.0,60.00,75.0,90.0

In [12]:
df.to_csv("../cleaned_data/traffic_cleaned.csv", index=False)