In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../datasets/IoT.csv")

In [3]:
df.head()

,Latitude,Longitude,Traffic_Speed_kmph,Traffic_Density_vpkm,FFT_Feature_1,FFT_Feature_2,FFT_Feature_3,Vehicle_Count,Time_of_Day_min,Congestion_Level
0,12.917964,77.623311,55.190066,41.483270,0.185443,0.838712,0.647059,17,852,0
1,13.088692,77.567956,52.085809,31.007323,0.069059,0.176809,0.758469,20,1048,0
2,13.066659,77.660855,37.627867,30.668128,0.264561,0.339073,0.074449,16,73,1
3,13.036142,77.617962,28.233521,29.649618,0.412920,0.286254,0.241308,16,209,1
4,13.082460,77.577661,22.363697,39.744264,0.306188,0.356061,0.769289,29,224,1

In [4]:
print("Shape of Dataset :", df.shape)

Shape of Dataset : (3876, 10)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3876 entries, 0 to 3875
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Latitude              3876 non-null   float64
 1   Longitude             3876 non-null   float64
 2   Traffic_Speed_kmph    3876 non-null   float64
 3   Traffic_Density_vpkm  3876 non-null   float64
 4   FFT_Feature_1         3876 non-null   float64
 5   FFT_Feature_2         3876 non-null   float64
 6   FFT_Feature_3         3876 non-null   float64
 7   Vehicle_Count         3876 non-null   int64
 8   Time_of_Day_min       3876 non-null   int64
 9   Congestion_Level      3876 non-null   int64
dtypes: float64(7), int64(3)
memory usage: 302.9 KB

In [6]:
df.columns.tolist()

['Latitude',
 'Longitude',
 'Traffic_Speed_kmph',
 'Traffic_Density_vpkm',
 'FFT_Feature_1',
 'FFT_Feature_2',
 'FFT_Feature_3',
 'Vehicle_Count',
 'Time_of_Day_min',
 'Congestion_Level']

In [7]:
df.describe()

,Latitude,Longitude,Traffic_Speed_kmph,Traffic_Density_vpkm,FFT_Feature_1,FFT_Feature_2,FFT_Feature_3,Vehicle_Count,Time_of_Day_min,Congestion_Level
count,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000
mean,12.999707,77.599694,40.049252,29.832492,0.501220,0.501889,0.501487,19.898091,730.191176,0.854747
std,0.057699,0.057945,10.057244,7.808380,0.287018,0.285896,0.289958,4.469387,413.142558,0.407422
min,12.900001,77.500036,0.000000,6.120604,0.000105,0.000765,0.000008,7.000000,0.000000,0.000000
25%,12.949019,77.549430,33.074630,24.390824,0.251071,0.259795,0.253836,17.000000,376.500000,1.000000
50%,13.000099,77.600010,39.919187,29.682486,0.505851,0.504521,0.502755,20.000000,724.500000,1.000000
75%,13.048546,77.649657,46.785903,35.142330,0.743428,0.749062,0.755958,23.000000,1092.500000,1.000000
max,13.099958,77.699854,80.155776,64.390861,0.999841,0.999769,0.999940,35.000000,1438.000000,2.000000

In [8]:
df.isnull().sum()

Latitude                0
Longitude               0
Traffic_Speed_kmph      0
Traffic_Density_vpkm    0
FFT_Feature_1           0
FFT_Feature_2           0
FFT_Feature_3           0
Vehicle_Count           0
Time_of_Day_min         0
Congestion_Level        0
dtype: int64

In [9]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

In [12]:
print(df.shape)

(3876, 10)

In [13]:
df.dtypes

Latitude                float64
Longitude               float64
Traffic_Speed_kmph      float64
Traffic_Density_vpkm    float64
FFT_Feature_1           float64
FFT_Feature_2           float64
FFT_Feature_3           float64
Vehicle_Count             int64
Time_of_Day_min           int64
Congestion_Level          int64
dtype: object

In [14]:
df.select_dtypes(include=['object']).columns

Index([], dtype='str')

In [15]:
df.select_dtypes(include=['number']).columns

Index(['Latitude', 'Longitude', 'Traffic_Speed_kmph', 'Traffic_Density_vpkm',
       'FFT_Feature_1', 'FFT_Feature_2', 'FFT_Feature_3', 'Vehicle_Count',
       'Time_of_Day_min', 'Congestion_Level'],
      dtype='str')

In [16]:
for col in df.columns:
    print("="*40)
    print(col)
    print(df[col].unique()[:10])

========================================
Latitude
[12.91796379 13.08869214 13.06665899 13.03614242 13.08246033 12.92784376
 12.93526295 12.95043052 12.94896231 12.96216965]
========================================
Longitude
[77.6233115  77.56795637 77.66085458 77.61796215 77.57766123 77.6967746
 77.5132462  77.61555726 77.69791366 77.63819053]
========================================
Traffic_Speed_kmph
[55.19006586 52.08580909 37.62786739 28.23352086 22.36369703 29.52553237
 43.21006599 38.52331946 30.63091562 36.0781746 ]
========================================
Traffic_Density_vpkm
[41.4832696  31.00732313 30.66812834 29.64961808 39.74426381 31.14084397
 42.38424892 31.16644711  8.60234688 40.1350505 ]
========================================
FFT_Feature_1
[0.18544272 0.06905918 0.26456119 0.41292033 0.30618842 0.83470971
 0.49302767 0.24612788 0.95019906 0.12506282]
========================================
FFT_Feature_2
[0.83871248 0.17680876 0.33907299 0.28625395 0.35606086 0.71427179
 0.40546558 0.75957668 0.64040314 0.36109918]
========================================
FFT_Feature_3
[0.64705916 0.75846889 0.07444852 0.24130756 0.76928869 0.37061597
 0.91081896 0.51767041 0.00102713 0.69883596]
========================================
Vehicle_Count
[17 20 16 29 13 27 12 15 21 23]
========================================
Time_of_Day_min
[ 852 1048   73  209  224  418  408  130  946  177]
========================================
Congestion_Level
[0 1 2]

In [17]:
df.columns.tolist()

['Latitude',
 'Longitude',
 'Traffic_Speed_kmph',
 'Traffic_Density_vpkm',
 'FFT_Feature_1',
 'FFT_Feature_2',
 'FFT_Feature_3',
 'Vehicle_Count',
 'Time_of_Day_min',
 'Congestion_Level']

In [18]:
print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

Rows    : 3876
Columns : 10

In [19]:
df.describe()

,Latitude,Longitude,Traffic_Speed_kmph,Traffic_Density_vpkm,FFT_Feature_1,FFT_Feature_2,FFT_Feature_3,Vehicle_Count,Time_of_Day_min,Congestion_Level
count,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000,3876.000000
mean,12.999707,77.599694,40.049252,29.832492,0.501220,0.501889,0.501487,19.898091,730.191176,0.854747
std,0.057699,0.057945,10.057244,7.808380,0.287018,0.285896,0.289958,4.469387,413.142558,0.407422
min,12.900001,77.500036,0.000000,6.120604,0.000105,0.000765,0.000008,7.000000,0.000000,0.000000
25%,12.949019,77.549430,33.074630,24.390824,0.251071,0.259795,0.253836,17.000000,376.500000,1.000000
50%,13.000099,77.600010,39.919187,29.682486,0.505851,0.504521,0.502755,20.000000,724.500000,1.000000
75%,13.048546,77.649657,46.785903,35.142330,0.743428,0.749062,0.755958,23.000000,1092.500000,1.000000
max,13.099958,77.699854,80.155776,64.390861,0.999841,0.999769,0.999940,35.000000,1438.000000,2.000000

In [20]:
df.isnull().sum()

Latitude                0
Longitude               0
Traffic_Speed_kmph      0
Traffic_Density_vpkm    0
FFT_Feature_1           0
FFT_Feature_2           0
FFT_Feature_3           0
Vehicle_Count           0
Time_of_Day_min         0
Congestion_Level        0
dtype: int64

In [21]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [22]:
df.dtypes

Latitude                float64
Longitude               float64
Traffic_Speed_kmph      float64
Traffic_Density_vpkm    float64
FFT_Feature_1           float64
FFT_Feature_2           float64
FFT_Feature_3           float64
Vehicle_Count             int64
Time_of_Day_min           int64
Congestion_Level          int64
dtype: object

In [23]:
df.nunique()

Latitude                3876
Longitude               3876
Traffic_Speed_kmph      3876
Traffic_Density_vpkm    3876
FFT_Feature_1           3876
FFT_Feature_2           3876
FFT_Feature_3           3876
Vehicle_Count             29
Time_of_Day_min         1331
Congestion_Level           3
dtype: int64

In [24]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Latitude,3876.0,12.999707,0.057699,12.900001,12.949019,13.000099,13.048546,13.099958
Longitude,3876.0,77.599694,0.057945,77.500036,77.549430,77.600010,77.649657,77.699854
Traffic_Speed_kmph,3876.0,40.049252,10.057244,0.000000,33.074630,39.919187,46.785903,80.155776
Traffic_Density_vpkm,3876.0,29.832492,7.808380,6.120604,24.390824,29.682486,35.142330,64.390861
FFT_Feature_1,3876.0,0.501220,0.287018,0.000105,0.251071,0.505851,0.743428,0.999841
FFT_Feature_2,3876.0,0.501889,0.285896,0.000765,0.259795,0.504521,0.749062,0.999769
FFT_Feature_3,3876.0,0.501487,0.289958,0.000008,0.253836,0.502755,0.755958,0.999940
Vehicle_Count,3876.0,19.898091,4.469387,7.000000,17.000000,20.000000,23.000000,35.000000
Time_of_Day_min,3876.0,730.191176,413.142558,0.000000,376.500000,724.500000,1092.500000,1438.000000
Congestion_Level,3876.0,0.854747,0.407422,0.000000,1.000000,1.000000,1.000000,2.000000

In [25]:
df["Congestion_Level"].value_counts()

Congestion_Level
1    3151
0     644
2      81
Name: count, dtype: int64

In [26]:
df.corr(numeric_only=True)

,Latitude,Longitude,Traffic_Speed_kmph,Traffic_Density_vpkm,FFT_Feature_1,FFT_Feature_2,FFT_Feature_3,Vehicle_Count,Time_of_Day_min,Congestion_Level
Latitude,1.000000,-0.007043,-0.009135,0.034312,-0.028008,-0.017541,-0.037610,-0.006620,-0.021909,0.008308
Longitude,-0.007043,1.000000,-0.006129,-0.014397,0.029045,-0.003936,-0.034066,-0.004534,0.006069,0.010111
Traffic_Speed_kmph,-0.009135,-0.006129,1.000000,0.032746,-0.005588,-0.000761,0.014872,-0.017928,-0.020132,-0.739544
Traffic_Density_vpkm,0.034312,-0.014397,0.032746,1.000000,0.011854,-0.003792,-0.012470,-0.007939,-0.000491,-0.025831
FFT_Feature_1,-0.028008,0.029045,-0.005588,0.011854,1.000000,-0.008093,0.000284,-0.000444,-0.007375,-0.008935
FFT_Feature_2,-0.017541,-0.003936,-0.000761,-0.003792,-0.008093,1.000000,-0.001485,-0.021804,0.007531,-0.003209
FFT_Feature_3,-0.037610,-0.034066,0.014872,-0.012470,0.000284,-0.001485,1.000000,-0.008544,0.007792,-0.003514
Vehicle_Count,-0.006620,-0.004534,-0.017928,-0.007939,-0.000444,-0.021804,-0.008544,1.000000,0.001980,0.026732
Time_of_Day_min,-0.021909,0.006069,-0.020132,-0.000491,-0.007375,0.007531,0.007792,0.001980,1.000000,0.008004
Congestion_Level,0.008308,0.010111,-0.739544,-0.025831,-0.008935,-0.003209,-0.003514,0.026732,0.008004,1.000000

In [27]:
df.to_csv("../cleaned_data/IoT_cleaned.csv", index=False)